### ISSUE TITLE
Unicode character breaks watchface

### ISSUE THREAD

**Issue by ianmarcinkowski** [andornaut/pebble-prime#1]
There is a unicode character that shows up some times which pushes the time to the right, resulting in something like `© 9…` as seen in the screenshot below.

![watchface](https://cloud.githubusercontent.com/assets/27977/16177786/8ebf7e52-3604-11e6-8e4c-b4b60c9d7912.jpg)

**Comment by andornaut** [comment]
Are you using v1. 0? If so, please try upgrading to 1.1.

**Comment by ianmarcinkowski** [comment]
I'm on ~~1.0~~ 1.2

**Comment by andornaut** [comment]
Please try deleting the watchface and re-downloading from the [Pebble app store](https://apps.getpebble.com/en_US/application/5764b04b3feaee913e000030).

This issue occurred with v1.0 because the empty-space character was not included in the font bundled with the watchface. That issue was subsequently fixed and independently confirmed, so I would expect it to work with the latest version - at least on a clean install.

Let me know if you're still experiencing this issue.

**Comment by ianmarcinkowski** [comment]
No longer having this issue!  Thanks!
